
-- table nha cung ung
CREATE TABLE NhaCungUng( id INT PRIMARY KEY AUTO_INCREMENT, MaCungUng VARCHAR(50), TenCungUng VARCHAR(50), SDT CHAR(50), Email VARCHAR(50), SanPham VARCHAR(50), DiaChi VARCHAR(50));
