CREATE TABLE Sinhvien(
    id INT PRIMARY KEY AUTO_INCREMENT,
    MaSV VARCHAR(50),
    TenSV VARCHAR(50),
    Lop VARCHAR(50),
    DiaChi VARCHAR(50),
    GioiTinh VARCHAR(50),
    Tuoi VARCHAR(50)
   );